main/authentication/models.py
from main.db import db
from datetime import datetime

class User(db.Model):
	__tablename__ = "users"
	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	name = db.Column(db.String(100))
	email = db.Column(db.String(100), nullable=False, unique=True)
	password = db.Column(db.String(100), nullable=False)
	created_at = db.Column(db.DateTime, default=datetime.now)
	updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

	def __init__(self, name, email, username, password,is_superuser=None):
		self.name = name
		self.email = email
		self.password = password

main/authentication/routes.py
from flask import Blueprint, render_template, url_for, request, flash, redirect, jsonify
from .utils import *
from datetime import datetime

from main.db import db
from main.Home.models import Status, TalaBandi
from sqlalchemy import desc

authentication = Blueprint("authentication", __name__, template_folder="templates")

@authentication.route("/", methods=['GET','POST'])
@login_not_required
def login():
	if request.method == "POST":
		email = request.form.get("email")
		password = request.form.get("password")

		if email == '' or email is None:
			flash("Email cannot be empty!")
		elif password == '' or password is None:
			flash("Password cannot be empty!")
		elif getUserByEmail(email) is None or getUserByEmail(email) == '':
			flash("Unauthorized access!")
		else:
			session['user'] = email 
			return redirect(url_for('authentication.admin_home'))

	return render_template("login.html")

@authentication.route("/admin/")
@login_required
def admin_home():
	username = getUserByEmail(session['user']).name
	talabandi_list = TalaBandi.query.order_by(desc(TalaBandi.date)).all()
	print(talabandi_list)
	return render_template("admin.html", username=username, talabandi_list=talabandi_list)

@authentication.route('/logout/')
@login_required
def logout():
	session.pop('user', None)
	return redirect(url_for('authentication.admin_home'))

@authentication.route("/add/talabandi/", methods=['POST'])
@login_required
def add_talabandi():
	date = request.form.get("talabandi_date")
	description = request.form.get("description")
	status = request.form.get("status")
	enddate = None

	_enddate = None

	if status == Status.COMPLETED.value:
		enddate = request.form.get("end_date")
		_enddate = strDateToPythonDate(enddate)


	_date = strDateToPythonDate(date)
	tithi = getTithi(_date)

	if date is None or date == '':
		flash("Date cannot be empty")
	elif status is None or status == '':
		flash("Status cannot be empty")
	else:
		if _date>datetime.now().date():
			flash("No future prediction please")
		elif checkTalabandiCollision(_date) and status==Status.ONGOING.value:
			flash("Talabandi date collision occured")
		elif isOngoingTalabandiNotBeforeLastEndTime(_date) and status==Status.ONGOING.value:
			flash("Ongoing cannot be before last talabandi")
		elif isTalabandiOngoing() and status==Status.ONGOING.value:
			flash("Talabandi is already ongoing")
		elif status==Status.COMPLETED.value:
			if TalabandiAlreadyExists(_date, _enddate):	
				flash("Talabandi already exists")
			else:
				save(_date,description,status,tithi,_enddate)
		else:
			save(_date,description,status,tithi, _enddate)		

	return redirect(url_for("authentication.admin_home"))


@authentication.route("/edit/<int:id>", methods=['GET','POST'])
@login_required
def edit_talabandi(id):
	res = TalaBandi.query.filter(TalaBandi.id==id, TalaBandi.status==Status.ONGOING.value).first()
	
	return render_template("edit.html",res=res)

@authentication.route('/delete-talabandi/', methods=['POST'])
def delete_talabandi():
	data = request.json
	talabandi_id = data.get('id')

	# Fetch the TalaBandi instance and delete it
	talabandi = TalaBandi.query.get(talabandi_id)
	print(talabandi)
	if talabandi:
		db.session.delete(talabandi)
		db.session.commit()
		return jsonify({"success": True, "message": "TalaBandi deleted successfully."})
	else:
		return jsonify({"success": False, "message": "TalaBandi not found."})

main/authentication/templates/admin.html
{%extends 'base.html'%}
{%block content%}

{% with messages = get_flashed_messages() %}
	{% if messages %}
		{% for msg in messages %}
			<script type="text/javascript">
				Swal.fire({
					title: "{{msg}}",
					width: 600,
					padding: "3em",
					color: "#fff",
					background: `
						rgba(0,0,0,0.5) url("{{url_for('static',filename='img/abhijeet.jpg')}}") no-repeat center center / contain
					`,
					
					backdrop: `
					  rgba(0,0,123,0.4)
					  url("{{url_for('static',filename='img/nyan-cat.gif')}}")
					  left top
					  no-repeat
					`
				  });
			</script>
		{% endfor %}
	{% endif %}
{% endwith %}

<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-one-quarter">
                <aside class="menu">
                    <p class="menu-label">
                        Options
                    </p>
                    <ul class="menu-list">
                        <li><a href="#" onclick="showSection('addTalabandi')">Add Talabandi</a></li>
                        <li><a href="#" onclick="showSection('listTalabandi')">List Talabandi</a></li>
                        <li><a href="#" onclick="showSection('addUser')">Add User</a></li>
                    </ul>
                </aside>
            </div>
            <div class="column">
                <h1 class="title">Welcome, {{username}}</h1>
                <!-- Content areas for different options -->
                <!-- For example, the content area for adding Talabandi -->
                <div class="box" id="addTalabandi" style="display: none;">
                    <h2 class="subtitle">Add Talabandi&nbsp;<span class="tag is-danger is-small">BUGS</span></h2>
					<div class="column is-vcentered">
						<form action="{{url_for('authentication.add_talabandi')}}" method="POST" id="talabandiForm">
							<div class="field">
								<label class="label">Talabandi Date</label>
								<div class="control">
									<input class="input" type="date" name="talabandi_date" required>
								</div>
							</div>
							<div class="field">
								<label class="label">Description</label>
								<div class="control">
									<textarea class="textarea" name="description" placeholder="Enter Description"></textarea>
								</div>
							</div>
							<div class="field">
								<label class="label">Status</label>
								<div class="control">
									<div class="select">
										<select name="status" id="statusSelect">
											<option value="ONGOING">Ongoing</option>
											<option value="COMPLETED">Completed</option>
										</select>
									</div>
								</div>
							</div>
							<div class="field">
								<label class="label">End Date</label>
								<div class="control">
									<input class="input" type="date" name="end_date" id="endDateInput" required>
								</div>
							</div>
							<div class="field is-grouped">
								<div class="control">
									<button class="button is-primary" type="submit">Add Talabandi</button>
								</div>
								<div class="control">
									<button class="button is-light" type="reset">Reset</button>
								</div>
							</div>
						</form>
					</div>
				</div>
					<script>
						// Get status select and end date input elements
						const statusSelect = document.getElementById('statusSelect');
						const endDateInput = document.getElementById('endDateInput');
						
						endDateInput.disabled = true;
						// Add event listener to status select
						statusSelect.addEventListener('change', function() {
							// Check if status is ongoing
							if (this.value === 'ONGOING') {
								// If ongoing, disable end date input
								endDateInput.disabled = true;
								// Clear end date value
								endDateInput.value = '';
							} else {
								// If completed, enable end date input
								endDateInput.disabled = false;
							}
						});
					</script>
                <!-- Content area for listing Talabandi -->
                <div class="box" id="listTalabandi" style="display: none;">
                    <h2 class="subtitle">List Talabandi</h2>
                    <!-- Table to display list of Talabandi with edit and delete actions -->
                    <!-- Example table code -->
					<div class="table-container">
						{% if talabandi_list %}
						<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
							<thead>
								<tr>
									<th>Date</th>
									<th>Description</th>
									<th>Tithi</th>
									<th>Status</th>
									<th colspan=2>Actions</th>
								</tr>
							</thead>
							<tbody>
								<!-- Table rows with Talabandi data -->
								<!-- Each row should have edit and delete actions -->
							{% for talabandi in talabandi_list %}
							<tr>
								<th>{{talabandi.date}}{%if talabandi.status.value == "COMPLETED"%}&nbsp;to&nbsp;{{talabandi.end_date}} {%endif%}</th>
								<th>{% if talabandi.description == ""%}-{%else%}{{talabandi.description}}{%endif%}</th>
								<th>{{talabandi.tithi}}</th>
								<th><span class="tag is-success">{{talabandi.status.value}}</span></th>
								<th>
									{%if talabandi.status.value == "ONGOING"%}
										<a href="{{url_for('authentication.edit_talabandi', id=talabandi.id)}}">Edit</a></th>
									{%else%}
										<span class="has-text-grey-light has-text-weight-light">Edit</span>
									{%endif%}
								<th><a href="#" class="delete-btn" data-id="{{talabandi.id}}">Delete</a></th>
							</tr>
							{% endfor %}
							</tbody>
						</table>
						{% else %}
							<p class="is-fullwidth">Looks like no data has been added yet</p>
						{% endif %}
					</div>
                </div>
                <!-- Content area for addUser -->
                <div class="box" id="addUser" style="display: none;">
                    <h2 class="subtitle">Add new User</h2>
                    <!-- Form fields to create new user -->
                    <!-- Example form code -->
                    <form action="#" method="POST">
                        <!-- Form fields for creating new user -->
						<div class="field">
							<label class="label">Name</label>
							<div class="control">
								<input class="input" type="text" name="name" placeholder="Enter your name" required>
							</div>
						</div>
						<div class="field">
							<label class="label">Email</label>
							<div class="control">
								<input class="input" type="email" name="email" placeholder="Enter your email" required>
							</div>
						</div>
						<div class="field">
							<label class="label">Password</label>
							<div class="control">
								<input class="input" type="password" name="password" placeholder="Enter your password" required>
							</div>
						</div>
						<div class="field is-grouped">
							<div class="control">
								<button class="button is-primary" type="submit">Submit</button>
							</div>
							<div class="control">
								<button class="button is-light" type="reset">Clear</button>
							</div>
						</div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    function showSection(sectionId) {
        // Hide all sections
        document.querySelectorAll('.box').forEach(function(section) {
            section.style.display = 'none';
        });
        // Show the selected section
        document.getElementById(sectionId).style.display = 'block';
    }
	
	document.querySelectorAll('.delete-btn').forEach(function(button) {
		button.addEventListener('click', function(e) {
			const id = e.target.getAttribute('data-id');
			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				icon: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!'
			}).then((result) => {
				if (result.isConfirmed) {
					// Send AJAX request to delete TalaBandi
					fetch('{{url_for('authentication.delete_talabandi')}}', {
						method: 'POST',
						headers: {
							'Content-Type': 'application/json',
						},
						body: JSON.stringify({ id: id }),
					})
					.then(response => response.json())
					.then(data => {
						if (data.success) {
							Swal.fire('Success!', data.message, 'success');
							location.reload()
						} else {
							Swal.fire('Error!', data.message, 'error');
						}
					});
				}
			});
		});
	});
	
</script>

{%endblock%}

main/authentication/templates/edit.html
{%extends 'base.html'%}
{%block content%}
<div class="section">
    <div class="column">
        <a href="{{ url_for('authentication.admin_home') }}" class="button is-dark is-small">
            <span class="icon">
                <i class="fas fa-arrow-left"></i>
            </span>
            <span>Back</span>
        </a>
        <div class="box" id="addTalabandi">
            <h2 class="subtitle">Add Talabandi</h2>
            <div class="column is-vcentered">
                <form action="{{url_for('authentication.add_talabandi')}}" method="POST" id="talabandiForm">
                    <div class="field">
                        <label class="label">Talabandi Date</label>
                        <div class="control">
                            <input class="input" type="date" name="talabandi_date" value="{{res.date}}" disabled>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Description</label>
                        <div class="control">
                            <textarea class="textarea" name="description" value="{{res.description}}" placeholder="Enter Description"></textarea>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">Status</label>
                        <div class="control">
                            <div class="select">
                                <select name="status" id="statusSelect">
                                    <option value="ONGOING">Ongoing</option>
                                    <option value="COMPLETED">Completed</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="field">
                        <label class="label">End Date</label>
                        <div class="control">
                            <input class="input" type="date" name="end_date" value="{{res['end_date']}}" id="endDateInput" required>
                        </div>
                    </div>
                    <div class="field is-grouped">
                        <div class="control">
                            <button class="button is-primary" type="submit">Add Talabandi</button>
                        </div>
                        <div class="control">
                            <button class="button is-light" type="reset">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
            <script>
                // Get status select and end date input elements
                const statusSelect = document.getElementById('statusSelect');
                const endDateInput = document.getElementById('endDateInput');
                
                endDateInput.disabled = true;
                // Add event listener to status select
                statusSelect.addEventListener('change', function() {
                    // Check if status is ongoing
                    if (this.value === 'ONGOING') {
                        // If ongoing, disable end date input
                        endDateInput.disabled = true;
                        // Clear end date value
                        endDateInput.value = '';
                    } else {
                        // If completed, enable end date input
                        endDateInput.disabled = false;
                    }
                });

            </script>
    </div>
</div>
{%endblock%}

main/authentication/templates/login.html
{%extends 'base.html'%}
{%block content%}
	{% with messages = get_flashed_messages() %}
        {% if messages %}
			{% for msg in messages %}
			  <script type="text/javascript">
				Swal.fire({
					title: "{{msg}}",
					width: 600,
					padding: "3em",
					color: "#fff",
					background: `
						rgba(0,0,0,0.5) url("{{url_for('static',filename='img/vivek.jpg')}}") no-repeat center center / contain
					`,
					
					backdrop: `
					  rgba(0,0,123,0.4)
					  url("{{url_for('static',filename='img/puneet.gif')}}")
					  left top
					  no-repeat
					`
				  });
			  </script>
        	{% endfor %}
        {% endif %}
    {% endwith %}
	<div class="section">
		<h1 class="title">Login</h1>
		<form action="{{url_for('authentication.login')}}" method="POST">
			<div class="field">
				<label class="label" for="email">Email:</label>
				<div class="control">
					<input class="input" type="email" id="email" name="email" required>
				</div>
			</div>
			<div class="field">
				<label class="label" for="password">Password:</label>
				<div class="control">
					<input class="input" type="password" id="password" name="password" required>
				</div>
			</div>
			<div class="field">
				<div class="control">
					<button class="button is-primary" type="submit">Login</button>
				</div>
			</div>
		</form>
	</div>
{%endblock%}