main/Home/models.py
from main.db import db 
from enum import Enum

class Status(Enum):
    ONGOING = 'ONGOING'
    COMPLETED = 'COMPLETED'

class TalaBandi(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    user = db.relationship('User', backref='talabandis')
    date = db.Column(db.Date)
    description = db.Column(db.Text, nullable=True)
    status = db.Column(db.Enum(Status), nullable=False, default=Status.ONGOING)
    end_date = db.Column(db.Date)
    tithi = db.Column(db.String(50))

    def __init__(self, user_id, date, description, status, tithi, end_date=None):
        self.user_id=user_id
        self.date=date
        self.description=description
        self.status=status
        self.end_date=end_date
        self.tithi=tithi

main/authentication/models.py
from main.db import db
from datetime import datetime

class User(db.Model):
	__tablename__ = "users"
	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	name = db.Column(db.String(100))
	email = db.Column(db.String(100), nullable=False, unique=True)
	password = db.Column(db.String(100), nullable=False)
	created_at = db.Column(db.DateTime, default=datetime.now)
	updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

	def __init__(self, name, email, username, password,is_superuser=None):
		self.name = name
		self.email = email
		self.password = password

main/Home/routes.py
from datetime import datetime
from main.authentication.utils import getLastTalabandi
from flask import Blueprint, render_template, url_for, request, flash
from .utils import *

from main.authentication.utils import getTithi
from sqlalchemy import desc

home = Blueprint("home", __name__, template_folder="templates")

@home.route("/", methods=['GET','POST'])
def index():
	# if request.method == "POST":
	# 	email = request.form.get("email")
	# 	password = request.form.get("password")

	# 	if email == '' or email is None:
	# 		flash("Email cannot be empty!")
	# 	elif password == '' or password is None:
	# 		flash("Password cannot be empty!")
	# 	elif getUserByEmail(email) is None or getUserByEmail(email) == '':
	# 		flash("Unauthorized access!")
	# 	else:
	# 		pass
	# 		print(email, password)
	talaState = isTalabandi()
	tithi = getTithi(datetime.now().date())
	return render_template("index.html", isTalabandi=talaState, tithi=tithi)

@home.route('/about/')
def about():
	return render_template('about.html')

@home.route('/stats/')
def stats():
	last = getLastTalabandi()
	stat=isTalabandi()
	ongoing = TalaBandi.query.filter(TalaBandi.status==Status.ONGOING).first()
	talabandi_list = TalaBandi.query.filter(TalaBandi.status!=Status.ONGOING).order_by(desc(TalaBandi.date)).all()
	return render_template('stats.html', last=last, isTalabandi=stat, talabandi_list=talabandi_list, ongoing=ongoing)
	

main/__init__.py
from flask import Flask
from .config import Config
from .db import init_db
from .create_superuser import create

from main.authentication.routes import authentication
from main.Home.routes import home

def create_app():
	app = Flask(__name__)
	app.config.from_object(Config)

	init_db(app)
	create()

	app.register_blueprint(authentication, url_prefix="/auth/")
	app.register_blueprint(home, url_prefix="/")

	return app

main/authentication/routes.py
from flask import Blueprint, render_template, url_for, request, flash, redirect, jsonify
from .utils import *
from datetime import datetime

from main.db import db
from main.Home.models import Status, TalaBandi
from sqlalchemy import desc

authentication = Blueprint("authentication", __name__, template_folder="templates")

@authentication.route("/", methods=['GET','POST'])
@login_not_required
def login():
	if request.method == "POST":
		email = request.form.get("email")
		password = request.form.get("password")

		if email == '' or email is None:
			flash("Email cannot be empty!")
		elif password == '' or password is None:
			flash("Password cannot be empty!")
		elif getUserByEmail(email) is None or getUserByEmail(email) == '':
			flash("Unauthorized access!")
		else:
			session['user'] = email 
			return redirect(url_for('authentication.admin_home'))

	return render_template("login.html")

@authentication.route("/admin/")
@login_required
def admin_home():
	username = getUserByEmail(session['user']).name
	talabandi_list = TalaBandi.query.order_by(desc(TalaBandi.date)).all()
	print(talabandi_list)
	return render_template("admin.html", username=username, talabandi_list=talabandi_list)

@authentication.route('/logout/')
@login_required
def logout():
	session.pop('user', None)
	return redirect(url_for('authentication.admin_home'))

@authentication.route("/add/talabandi/", methods=['POST'])
@login_required
def add_talabandi():
	date = request.form.get("talabandi_date")
	description = request.form.get("description")
	status = request.form.get("status")
	enddate = None

	_enddate = None

	if status == Status.COMPLETED.value:
		enddate = request.form.get("end_date")
		_enddate = strDateToPythonDate(enddate)


	_date = strDateToPythonDate(date)
	tithi = getTithi(_date)

	if date is None or date == '':
		flash("Date cannot be empty")
	elif status is None or status == '':
		flash("Status cannot be empty")
	else:
		if _date>datetime.now().date():
			flash("No future prediction please")
		elif checkTalabandiCollision(_date) and status==Status.ONGOING.value:
			flash("Talabandi date collision occured")
		elif isOngoingTalabandiNotBeforeLastEndTime(_date) and status==Status.ONGOING.value:
			flash("Ongoing cannot be before last talabandi")
		elif isTalabandiOngoing() and status==Status.ONGOING.value:
			flash("Talabandi is already ongoing")
		elif status==Status.COMPLETED.value:
			if TalabandiAlreadyExists(_date, _enddate):	
				flash("Talabandi already exists")
			else:
				save(_date,description,status,tithi,_enddate)
		else:
			save(_date,description,status,tithi, _enddate)		

	return redirect(url_for("authentication.admin_home"))


@authentication.route("/edit/<int:id>", methods=['GET','POST'])
@login_required
def edit_talabandi(id):
	res = TalaBandi.query.filter(TalaBandi.id==id, TalaBandi.status==Status.ONGOING.value).first()
	
	return render_template("edit.html",res=res)

@authentication.route('/delete-talabandi/', methods=['POST'])
def delete_talabandi():
	data = request.json
	talabandi_id = data.get('id')

	# Fetch the TalaBandi instance and delete it
	talabandi = TalaBandi.query.get(talabandi_id)
	print(talabandi)
	if talabandi:
		db.session.delete(talabandi)
		db.session.commit()
		return jsonify({"success": True, "message": "TalaBandi deleted successfully."})
	else:
		return jsonify({"success": False, "message": "TalaBandi not found."})

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PULocks</title>
    <link rel="stylesheet" href="{{url_for('static', filename='bulma/css/bulma.min.css')}}">

    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <script src="{{url_for('static',filename='js/sweetalert2@11.js')}}"></script>
</head>
<body>
<div class="container">
    <header>
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="{{url_for('home.index')}}">
                    PULOCKS &nbsp;<span class="tag is-warning">Alpha</span>&nbsp;<span class="tag is-danger">INCOMPLETE</span>
                </a>

                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar-items-list">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbar-items-list" class="navbar-menu">
                <div class="navbar-end">
                    <a class="navbar-item" href="{{url_for('home.index')}}">
                        Home
                    </a>
                    <a class="navbar-item" href="{{url_for('home.stats')}}">
                        Stats
                    </a>
                    <a class="navbar-item" href="{{url_for('home.about')}}">
                        About
                    </a>
                    {% if session['user'] %}
                    <a class="navbar-item" href="{{url_for('authentication.admin_home')}}">
                        Profile
                    </a>
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-dark" href="{{url_for('authentication.logout')}}">
                                Logout
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-dark" href="{{url_for('authentication.login')}}">
                                Login
                            </a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>
    {%block content%}{%endblock%}
    
    <footer class="has-background-dark has-text-grey-lighter" style="width: 100%; max-width: 100%; position: fixed; bottom: 0; left: 0; z-index: 100;">
        <div class="content has-text-centered footer_content">With ❤️ from BE Computer</div>
    </footer>
  </div>
  
  <!-- Add Bulma's JavaScript -->
  <script defer src="{{url_for('static', filename='js/fontawesome.js')}}"></script>
  <script>
      // Add JavaScript to toggle the navbar menu
      document.addEventListener('DOMContentLoaded', function () {
  
          // Get all "navbar-burger" elements
          var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
  
          // Check if there are any navbar burgers
          if ($navbarBurgers.length > 0) {
  
              // Add a click event on each of them
              $navbarBurgers.forEach(function ($el) {
                  $el.addEventListener('click', function () {
  
                      // Get the target from the "data-target" attribute
                      var target = $el.dataset.target;
                      var $target = document.getElementById(target);
  
                      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                      $el.classList.toggle('is-active');
                      $target.classList.toggle('is-active');
  
                  });
              });
          }
  
      });
  </script>
</body>
</html>